const TrinidadStudios = [
  {
    id: '1',
    etage: '1er étage',
    numero: 'S.01',
    image: require('../assets/plan.jpg'),
    surface:'30m²',
    parking:'  0m²',
    terrasse:'  1m²',
    price:'820.000 dhs',
  },
  {
    id: '2',
    etage: '1er étage',
    numero: 'S.02',
    image: require('../assets/plan.jpg'),
    surface:'38m²' ,
    parking:'  0m²',
    terrasse:'  2m²',
    price:'950.000 dhs',
   },
  {
    id: '3',
    etage: '2eme étage',
    numero: 'S.06',
    image: require('../assets/plan.jpg'),
    surface:'38m²' ,
    parking:'  0m²',
    terrasse:'  2m²',
    price:'970.000 dhs',
   },
  {
    id: '4',
    etage: '3eme étage',
    numero: 'S.09',
    image: require('../assets/plan.jpg'),
    surface:'30m²',
    parking:'  0m²',
    terrasse:' 1m²',
    price:'855.000 dhs',
    },
  {
    id: '5',
    etage: '3eme étage',
    numero: 'S.10',
    image: require('../assets/plan.jpg'),
    surface:'38m²' ,
    parking:'  0m²',
    terrasse:' 2m²',
    price:'985.000 dhs',
   },
   {
    id: '6',
    etage: '4eme étage',
    numero: 'S.13',
    image: require('../assets/plan.jpg'),
    surface:'30m²' ,
    parking:'  0m²',
    terrasse:' 1m²',
    price:'870.000 dhs',
   },
   {
    id: '7',
    etage: '5eme étage',
    numero: 'S.17',
    image: require('../assets/plan.jpg'),
    surface:'30m²' ,
    parking:'  0m²',
    terrasse:' 1m²',
    price:'900.000 dhs',
   },
];

export default TrinidadStudios;
